### ISSUE TITLE
DEX EventHub to Databricks 

### ISSUE THREAD

**Issue by raman-cdc** [CDCgov/data-exchange-hl7#159]
Enable connectivity between EDAV Databricks and DEX Eventhub 

- [x]  completion criteria: For testing purposes and to complete for demonstration: Create a notebook in Databricks and pull from EventHub

**Comment by boris-ning-usds** [comment]
The direction will be from EDAV Databricks to pull/read from DEX Eventhub.

We'll need to ask the EDAV team to create a private endpoint to our DEX Eventhub in order to pull the data, similar to the [read tweets scenario](https://learn.microsoft.com/en-us/azure/databricks/scenarios/databricks-stream-from-eventhubs#read-tweets-from-event-hubs).

**Comment by boris-ning-usds** [comment]
Filing a Cloud Service Request - REQ0059485 / RITM0059503 to grant our dev environment Service Principal (for coordination with EDAV) with an Azure Event Hubs Sender and Azure Event Hubs Receiver roles.

**Comment by raman-cdc** [comment]
Troubleshooting with EDAV team on below error while reading Eventhub data

py4j.security.Py4JSecurityException: Method public org.apache.spark.sql.streaming.DataStreamReader org.apache.spark.sql.SQLContext.readStream() is not whitelisted on class class org.apache.spark.sql.SQLContext
