### ISSUE TITLE
Integration of blanket processing rules into MMG Validator

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#195]
This ticket is to implement the two rules that are not already covered:
1. OBX-3 + OBX-4 combination must be unique for each OBR group
2. OBX-4 must be populated for segments in a repeating group.
The decision process is documented in #196

**Comment by mscaldas2012** [comment]
Currently, we're implementing bullet 1 - OBX-3 + OBX-4 combination must be unique for each OBR group - as a cardinality match. Because we validate the cardinality by group, therefore if we have the same OBX-3 within a group (a.k.a, OBX-4), then the cardinality of [?..1] is violated and a ERROR/Warning is raised.

bullet number two needs to be implemented and theres a ticket for that - #429
