### ISSUE TITLE
Discovery and planning for integration of Hepatitis into pipeline

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#243]
Discover and document:

What MMGs are used by Hepatitis program?
What conditions are covered by the Hepatitis MMGs?
What are nuances with Hepatitis MMGs - tabs with various Hepatitis versions (e.g., A, B, C, Perinatal Hep C, etc)?
How does GenV2 interact with Hepatitis MMGs?  
Define what needs to be done to integrate Hep into the HL7v2 pipeline.

**Comment by mscaldas2012** [comment]
Pipeline is fully capable of structure and MMG validating the current HEP MMGs (without Lab templates)

**Comment by marcia-schulman** [comment]
Q: What MMGs are used by Hepatitis program?
A: There are 2 MMG spreadsheets available to STLTs to implement: v1.0 and v1.0.1.  The content in regard to implementation is the same (v.1.0.1 only has some minor documentation updates), so we are using the tabs from the v.1.0 spreadsheet.

Q: What conditions are covered by the Hepatitis MMGs?
A: 
Condition Code | Condition Name
---------------|------------------
10100 |	Hepatitis B; acute 
10101 |	Hepatitis C; acute 
10103 |	Hepatitis E; acute 
10104 |	Hepatitis B; perinatal infection 
10105 |	Hepatitis B virus infection; chronic 
10106 |	Hepatitis C; Chronic 
10110 |	Hepatitis A; acute 
50248 |	Hepatitis C; perinatal infection 

Q: What are nuances with Hepatitis MMGs - tabs with various Hepatitis versions (e.g., A, B, C, Perinatal Hep C, etc)?
A: The Hepatitis MMGs that are in use right now are not available for download from MMGAT, so we had to "jsonify" the Hepatitis MMG v1.0 spreadsheet and treat it like a legacy MMG. Additionally, there are individual tabs in the spreadsheet that represent different MMGs for the different conditions. Each tab had to be extracted and converted to JSON with a unique name that identifies the version and the condition that it was designed to capture.
In addition, some hepatitis conditions use only the "Hepatitis Core", while others use a combination of Hepatitis Core and a condition-specific hep MMG. We have documented how these map within our condition codes table.
Another nuance is that Hepatitis Core includes an "Optional Lab Template" section. We decided that for now, since we are not validating content of the lab template MMG, we would omit this section from Hepatitis Core and revisit it later when we attempt to validate lab data.

Q: How does GenV2 interact with Hepatitis MMGs?
A: Each hep condition does use GenV2 as a basis. So a hep condition may have up to 3 MMGs in use: GenV2 + Hepatitis Core + one of the other tabs.

Q: Define what needs to be done to integrate Hep into the HL7v2 pipeline.
A: The following steps were taken to include Hep in the pipeline:
1. Convert each tab in the Hepatitis MMG v1.0 spreadsheet into an MMGAT-style JSON document and remove the Optional Lab Template section from Hepatitis Core.
2. Include these JSON documents as part of the "legacy_mmgs" resource cache so they will be imported into Redis by the MMGAT function.
3. Test to ensure that MMG Validation works.
These steps have been completed.
