### ISSUE TITLE
Condition Code lookup for MMG-Based condition

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#360]
Currently, GenV2 does not lnclude a Value Set code to lookup valid conditions on PHIN Vads, and therefore, the MMG-Based schema does not have the cdc_concept_name and preferred concept name for condition.
![image](https://user-images.githubusercontent.com/3239945/205157542-ee3be785-1b43-4f05-b958-e516c214d984.png)

One option would be to add PHVS_NotifiableEvent_Disease_Condition_CDC_NNDSS as the value set lookup for condition code on our GenV2 MMG.

- [ ] Determine if this should be used on other MMGs (GenV1, legacy, etc)
- [ ] Make sure the above Value set is indeed inclusive of all and any condition we might encounter (today for lyme/arbo/hep as well as for tomorrow - all programs?)

**Comment by marcia-schulman** [comment]
Question:
- Do we even need to provide "concept name" and "preferred concept name" for the values in OBR-31 (event code)?
[ ] Yes  [ ] No

If Yes, which option is preferred?
[ ] Option A: Query the value set PHVS_NotifiableEvent_Disease_Condition_CDC_NNDSS for this information. Note that the query would be against the latest version of this value set and therefore may not include event codes that were previously on the NND list but have since been dropped.

[ ] Option B: Integrate the values from PHVS_NotifiableEvent_Disease_Condition_CDC_NNDSS current and prior versions into the condition code-to-MMG mapping table in Redis. This would mean compiling a separate "database" of sorts that combines the values from this value set with MVPS routing information for these conditions along with input from programs regarding conditions they receive that are not on the NND list.

**Comment by marcia-schulman** [comment]
Per Leslyn:
Use the MVPS mapping from the NNDSS spreadsheet found [here](https://ndc.services.cdc.gov/wp-content/uploads/National_Notifiable_Diseases_Surveillance_System_Event_Code_List_2022_v1_2022JAN05.xlsx) for both condition code validation and name/preferred name.
NOTE: this information IS what was used to create the condition-to-mmg Redis table.

**Comment by marcia-schulman** [comment]
Per Leslyn:
YES we should error out any message that does not have an event code that is in the list above.
