### ISSUE TITLE
Review the current validation on sender OID to make sure it matches with MVPS.  

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#521]

**Comment by mscaldas2012** [comment]
I don't know if "matches" MVPS is the Goal here...

I understand OIDs with .TBD are supported by MVPS - but here are the questions I posed:
-	Is that OID used in Production? Is it associated with a valid Jurisdiction that sends data? Or is it just for testing?
-	If the latter, can we improve our testing and keep the rule “as is” instead of having to add extra lines of code or modify the logic in any way just to accommodate something that does not happen in prod?
