### ISSUE TITLE
Review the document provided by MVPS on functional requirements and identify gaps on blanket processing rules implemented in DEX

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#522]
Attached is the file provided by MVPS that contains all of their functional requirements. Will need to review to identify the gaps.

**Comment by mscaldas2012** [comment]
We did extensive work on mapping the MVPS rules to what we implemented, discussed several GAPS and have worked hours and hours on this.

Because this is so time consuming, I suggest that we get production data - which we are close to get with PHINMS - and run that data through our pipeline and discuss actual results that we see on reports generated from this data instead of going over the mapping one more time.
