### ISSUE TITLE
Terraform Dev tempedehl7 EventHub

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#54]
Need to create terraform for our EventHub infrastructure for HL7 ingestion.
Manually created tempedehl7 - this needs to be replaced by a terraform created resource.

Config:
- [X] DEV -> Pricing Tier: Basic (no support for capture or retention) $ 11/TU/month
- TST -> Pricing Tier: Std $22 /TU/Month
- STG -> Pricing Tier: Std 
- PRD -> Pricing Tier: Std

**Comment by boris-ning-usds** [comment]
I would like to break this task out to focus on just the "dev" environment and focus on the other environments at a later time. This is simple to do once we have one environment up and running, as it's simply changing the "sku" parameter from "Basic" to "Standard" for the other environments.

For the other environments, we may also need to discuss capacity.

**Comment by boris-ning-usds** [comment]
This ticket is completed for the DEV environment and available to be used with a function app.
I am currently testing it out with @cosmycx's receiver debatcher message processor (rdmp) function.

Caveats when spinning up Eventhub.
1. For the DEV environment, in order to have private endpoint enabled, it must be at least a Standard SKU, instead of Basic. This allows traffic to be internal only, and not available over public internet directly
1. I need to complete #55 - a creation of a storage account for the function app in order to fully test out the receiver debatcher function application. Right now, Eventhub is just sitting on the side without a way to be tested.
