### ISSUE TITLE
Terraform Function Apps for DEV

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#67]
Create Terraform scripts to instantiate a Function App:
Use new storage account (recommended by MS)
Use new App Insights (recommended by MS)

We are using 3 Function apps:
hl7-structure-validation (for scala)
hl7-mmg-vocab
hl7-rdmp

Completion criteria: terraformed the function and deployed app code to those functions (Azure function and function app).  Does not include CI/CD.

**Comment by boris-ning-usds** [comment]
This ticket may need better criteria since it was written a while ago - since this may be more like an Epic ticket.
I also recommend breaking up multiple tickets between the environments, since the other environment will require additional sizing to complete. Production will be a lot larger than Dev, for example - and require us to do some more testing to properly size our environment (Eventhub, Redis, storage account limitation, etc).


I am working with the vocab functions that @dtx0111 and @mscaldas2012 wrote; and those are now Terraform'd (Redis, storage account, and function app).
I am also working on the receiver debatcher message process (rdmp) function app and gotten Eventhub setup - and working in progress to get it up and running as part of #147.

**Comment by boris-ning-usds** [comment]
Dragging Cosmin into this ticket - since he's the one using all the functions app that I built.
I'm also picking up any request from him via #235.

**Comment by boris-ning-usds** [comment]
From what I know, this ticket's requirement is completed. All the functions were moved over to terraform'd function app.
