### ISSUE TITLE
Inconsistent JSON field name for message type

### ISSUE THREAD

**Issue by marcia-schulman** [CDCgov/data-exchange-hl7#785]
JSON for message_info section coming from receiver-debatcher function by way of DexMessageInfo object uses "type" as the field name for message type:

```json
"message_info":{"event_code":"10190","route":"pertussis","mmgs":["mmg:generic_mmg_v2_0","mmg:pertussis"],"reporting_jurisdiction":"05","type":"CASE"}
```
Downstream functions are looking for "message_type", not "type". It looks like "message_type" is what is being used by transport. This inconsistency needs to be resolved

**Comment by mscaldas2012** [comment]
The message type is defined at lib-dex-commons, and therefore reused across all functions:
![image](https://user-images.githubusercontent.com/3239945/231250356-f576d8d5-2c54-4571-8da4-a9c7ff8b0c52.png)

So the correct metadata is **message_info.type** 

The current transport service defines the metadata as message_type (because is not encapsulated within message_info):
![image](https://user-images.githubusercontent.com/3239945/231250952-c7da3d3b-1588-4a5c-83ec-1fbbd8412ac6.png)


(And this transport service is temporary - not a production service, we will use Dex UPload and other services to receive data.)

but, regardless of what service is uploading a file, the metadata at the Azure object needs to be set as follows:
(The receiver debatcher will load those object metadata and set them as dex metadata accordingly.

![image](https://user-images.githubusercontent.com/3239945/231251851-8f2e01f6-a9ab-4785-bf08-5ee39fb88d7f.png)

**Comment by mscaldas2012** [comment]
Found one inconsistency on redactor - fixing it right now.
Also, added type as attribute to the schema in DBX
