### ISSUE TITLE
phin-vocab fn- Test REST API

### ISSUE THREAD

**Issue by dtx0111** [CDCgov/data-exchange-hl7#83]
Need to test new REST API on phinvads.
Currently, function phin-vocab is accessing phinvads webservice api to fetch vocab data using Hessian jar.
Phinvads dev team suggested to try new Rest API, so planning to test it & apply it on azure phinvocab function.

Document metrics for REST API as compared to Hessian API.
Document needs and wants by DEX team for NNDSS.

For product owner use:
Need by DEX from NNDSS:
SLA to support milliseconds results for a query on a value set.  We should be able to do hundreds of requests per minute.  Is this realistic with current PHIN VADS solutions (APIs) in place (FY22-23)?

***Decision to be confirmed:  DEX needs to maintain cache until new vocabulary solution put in place at the agency in (FY23-24).

**Comment by rmharrison** [comment]
Stale issue.

MMG Validation was removed from DEX HL7v2 Validation pipeline on 9 Aug 2023 in [v0.0.25](https://github.com/CDCgov/data-exchange-hl7/blob/v0.0.25/CHANGELOG.md)

Briefly, the data flow was:
PHIN-MS API --> "phin-vocab" --> REDIS --> MMG Validator

"phin-vocab" was not required for non-MMG validation and was therefore removed.

I use "phin-vocab" in quotes because the folder structure changed a few times.
"phin-vocab" was the original folder name containing the VocabClient.kt. The folder reorganization history is as follows...
- 9 Aug 2023: Deleted in v0.0.25
- 05 Jun 2023: https://github.com/CDCgov/data-exchange-hl7/blob/v0.0.21/fn-cache-loader/src/main/kotlin/gov/cdc/dex/mrr/VocabClient.kt
- 15 Feb 2023: https://github.com/CDCgov/data-exchange-hl7/blob/v0.0.20/mrr/src/main/kotlin/gov/cdc/dex/mrr/VocabClient.kt
- 02 Nov 2022: https://github.com/CDCgov/data-exchange-hl7/blob/v0.0.6/mrr/src/main/java/gov/cdc/dex/mrr/VocabClient.kt
- 21 Sep 2022: https://github.com/CDCgov/data-exchange-hl7/blob/v0.0.5/phin-vocab/src/main/java/cdc/gov/phinvads/vocab/VocabClient.kt

As of 26 June 2024 in v0.0.48, very stale VocabClient.kt code resides in the "spikes" folder, https://github.com/CDCgov/data-exchange-hl7/blob/develop/spikes/phin-vocab/src/main/java/cdc/gov/phinvads/vocab/VocabClient.kt

Don't use the spikes VocabClient.kt
Use the code before deletion: https://github.com/CDCgov/data-exchange-hl7/blob/v0.0.24/fn-cache-loader/src/main/kotlin/gov/cdc/dex/mrr/VocabClient.kt
