### ISSUE TITLE
SPIKE: Migrate Fn to Java 17

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#941]
Validate if we can migrate to Java 17 (latest LTS version). Azure indicates is supported. we need to see if we can migrate towards that!

**Comment by emilio32-lang** [comment]
[upgrade java17-kotlin18.txt](https://github.com/CDCgov/data-exchange-hl7/files/11498808/upgrade.java17-kotlin18.txt)
Attached is a readme type file on the technical side of the java and kotlin upgrade.
For the upgrade itself, it should not take more than a sprint,  mostly because of testing.
It is possible to be done fn by fn as they run in their own runtime
