### ISSUE TITLE
GENv1 HL7 Validations:  Incorrect value on OBR-4 returns 2 errors. 

### ISSUE THREAD

**Issue by nadiackhan** [CDCgov/data-exchange-hl7#944]
**Test Message:** [https://app.zenhub.com/files/510836864/9cf5c162-3237-449e-8b90-ddf9ad9dccb0/download](https://app.zenhub.com/files/510836864/9cf5c162-3237-449e-8b90-ddf9ad9dccb0/download)
1. Using the MMG Validator, validate a Genv1 message with an incorrect value for OBR-4 
![image.png](https://images.zenhubusercontent.com/63daba99ae9e054f0b7aefb2/d6baa99c-4b77-4119-9f10-f7b900167b45)

2. Verify that an error is returned. 

**Actual result:**  Incorrect value on OBR-4 returns 2 errors. 
![image.png](https://images.zenhubusercontent.com/63daba99ae9e054f0b7aefb2/c8d8cabc-243e-4b5a-ad0a-3048c4410fc7)

**Expected result:** One error should be returned. 

**NOTE: See attached test message**

**Comment by mscaldas2012** [comment]
The issue here is that we ignore the "obrPosition" attribute from the MMG definition.

When getting values, we'll have to start using obrPosition when grabbing fields from OBR segments.

![image.png](https://images.zenhubusercontent.com/62fe6e64b6093409a06fd538/ddd4e253-1226-48c4-8762-228c5fa35ec1)

versus
![image.png](https://images.zenhubusercontent.com/62fe6e64b6093409a06fd538/62da7a74-5636-4297-ac23-0a032ae931aa)
